# Generated by Django 3.1 on 2021-01-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210118_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',)},
        ),
    ]
